name: cooking_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  auto_route: ^3.2.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  flutter_svg: ^1.0.3
  logger: ^1.1.0
  dots_indicator: ^2.1.0
  get: ^4.6.5
  json_annotation: ^4.5.0
  global_configs: ^1.1.2
  http: ^0.13.5

  
  dio: ^4.0.6
  basic_utils: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.9
  auto_route_generator: ^3.2.3
  freezed: ^1.1.1
  flutter_lints: ^1.0.0
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset:  assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
         
         
       
        
 